### ISSUE TITLE
Auswählen eigener Resourcen

### ISSUE THREAD

**Issue by Helrunar** [heimrichhannot/contao-api-bundle#4]
Ich habe eine eigene Resource angelegt, kann diese im Backend jedoch nicht auswählen, bzw sie erscheint dort nicht einmal (wenn es denn läuft, sie anderer Issue)

**Comment by fatcrobat** [comment]
Vermutlich selbiges Problem, composer dumpautoload aufrufen und dem Autoloader die Klasse mitteilen.

**Comment by Helrunar** [comment]
Nope, keine Veränderung

**Comment by fatcrobat** [comment]
@Helrunar 

Die Auswahl von Resourcen funktioniert, leider fehlte in der Doku der Hinweis, dass man die Konfiguration in der config.yml erweitern muss. Bitte vorher dennoch ein Update auf Version `2.0.1` ausführen.

Wir haben die README.md entsprechend erweiteret:

## Resource /api/resource/{resource_alias}

To add your custom resource, simply add an service within your bundles or app `services.yml`:

```
services:
	my.api.resource.my_resource:
		class: MyApi\Resource\MyResource
		arguments:
              - "my_resource"
		tags:
		- { name: huh.api.resource, alias: my_resource}
```

And register your resource configuration within your bundles or app `config.yml`:

```
huh:
  api:
    resources:
      - {name: my_resource, type: entity_resource, modelClass: "MyResourceModel", verboseName: my_resource}
```

To get your `config.yml` loaded properly, your `Plugin` class must implement the interface `Contao\ManagerPlugin\Config\ExtensionPluginInterface`:

```
namespace MyApi\ContaoManager;

use Contao\ManagerPlugin\Config\ContainerBuilder;
use Contao\ManagerPlugin\Config\ExtensionPluginInterface;
use HeimrichHannot\UtilsBundle\Container\ContainerUtil;

class Plugin implements ExtensionPluginInterface
{

    /**
     * {@inheritdoc}
     */
    public function getExtensionConfig($extensionName, array $extensionConfigs, ContainerBuilder $container)
    {
        return ContainerUtil::mergeConfigFile(
            'huh_api',
            $extensionName,
            $extensionConfigs,
            __DIR__.'/../Resources/config/config.yml'
        );
    }
```

**Do not forget to clear the symfony cache afterwards!**

**Comment by Helrunar** [comment]
Ich bekomme es wirklich nicht zum Laufen ... Ich habe nun upgedatet auf 2.0.1, alle Änderungen eingetragen, Cache (mehrfach) geleert, bekomme weiterhin nichts an eigener Resource zum Auswählen angezeigt ...

Meine service.yaml:

```
services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]
    omr.api.resource.data_export:
        class: Omr\OmrApiWrapper\ApiResources\DataExportResources
        arguments:
            - "data_export"
        tags:
            - { name: huh.api.resource, alias: data_export}
```

Meine Plugin.php:

```
<?php

namespace Omr\OmrApiWrapper\ContaoManager;

use Contao\CoreBundle\ContaoCoreBundle;
use Contao\ManagerPlugin\Bundle\BundlePluginInterface;
use Contao\ManagerPlugin\Config\ContainerBuilder;
use Contao\ManagerPlugin\Config\ExtensionPluginInterface;
use HeimrichHannot\UtilsBundle\Container\ContainerUtil;
use Contao\ManagerPlugin\Bundle\Config\BundleConfig;
use Contao\ManagerPlugin\Bundle\Parser\ParserInterface;
use Omr\OmrApiWrapper\OmrApiWrapperBundle;

class Plugin implements ExtensionPluginInterface
{
    /**
     * {@inheritdoc}
     */
    public function getBundles(ParserInterface $parser)
    {
        return [
            BundleConfig::create(OmrApiWrapperBundle::class)
                ->setLoadAfter([ContaoCoreBundle::class]),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getExtensionConfig($extensionName, array $extensionConfigs, ContainerBuilder $container)
    {
        return ContainerUtil::mergeConfigFile(
            'huh_api',
            $extensionName,
            $extensionConfigs,
            __DIR__.'/../Resources/config/config.yml'
        );
    }
}
```


Meine config.yaml
```
huh:
  api:
    resources:
      - {name: data_export, type: resource}
```
